import type { ResortData } from '~/types'

export default defineEventHandler((): ResortData => {
  return {
    name: 'Mega Resort Karimunjawa',
    tagline: 'A Hidden Paradise in the Java Sea',
    location: 'Karimunjawa Archipelago, Indonesia',
    heroDescription: 'Karimunjawa is a hidden paradise in the Java Sea, Indonesia. An archipelago of 27 islands, it offers pristine beaches, crystal-clear waters, vibrant coral reefs, and lush tropical landscapes with breathtaking ocean horizons.',
    aboutDescription: 'Nestled within the serene and pristine archipelago of Karimunjawa, Mega Resort offers an exclusive haven for discerning travelers seeking tranquility, luxury, and authentic Indonesian hospitality. Wake up to gentle ocean breezes and unobstructed panoramic sea views.',
    stats: [
      {
        value: '20+',
        label: 'Unique Overwater Villas',
      },
      {
        value: '98%',
        label: 'Customer Satisfaction',
      },
      {
        value: '50+',
        label: 'Curated Island & Ocean Activities',
      },
    ],
    videoBanner: {
      title: 'Mega Resort Karimunjawa',
      description: 'Immerse yourself in breathtaking sunsets, vibrant coral reefs, and authentic island warmth. Surrounded by crystal-clear waters and lush greenery, Mega Resort Karimunjawa offers an idyllic sanctuary where nature meets luxury.',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1600&q=80',
    },
    gallery: [
      {
        id: 1,
        title: 'Tropical Waters & Overwater Deck',
        category: 'Villa & Scenery',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
        description: 'Serene evenings over the wooden deck with panoramic sunset views.'
      },
      {
        id: 2,
        title: 'Sunset Over Lagoon Walkway',
        category: 'Resort Walkway',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        description: 'Connecting pathways between water suites and the tropical island.'
      },
      {
        id: 3,
        title: 'Overwater Bungalow Experience',
        category: 'Guest Moments',
        image: '/images/about-resort.jpg',
        description: 'Unwind on the private villa terrace overlooking crystal blue waters.'
      },
      {
        id: 4,
        title: 'Overwater Villa Pavilion',
        category: 'Architecture',
        image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80',
        description: 'Traditional tropical woodcraft blended with coastal luxury.'
      },
      {
        id: 5,
        title: 'Lagoon Wooden Boardwalk',
        category: 'Exterior',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        description: 'Pristine ocean waters under wooden stilt villas.'
      },
    ],
    villas: [
      {
        id: 1,
        name: 'Mega Panorama Suite',
        tagline: 'Oceanfront Luxury with Private Balcony',
        description: 'Featuring hand-carved teak accents, an open-air lounge, hanging rattan swing chair, and direct lagoon views with gentle tropical breezes.',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80',
        capacity: '2-4 Guests',
        bedType: 'King Size Bed',
        features: ['Ocean Front Terrace', 'Hanging Rattan Swing', 'Ensuite Rain Shower', 'Complimentary Minibar', 'High-Speed Wi-Fi'],
        pricePerNight: 2750000,
      },
      {
        id: 2,
        name: 'Royal Water Villa',
        tagline: 'Perched Directly Above the Turquoise Lagoon',
        description: 'Private sun deck with direct water access ladder, glass floor viewing panel, and uninterrupted sunset vistas.',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=80',
        capacity: '2 Guests',
        bedType: 'Super King Bed',
        features: ['Direct Water Access', 'Glass Floor Panel', 'Bathtub with Ocean View', 'Sunset Facing Deck', '24/7 Butler Service'],
        pricePerNight: 3950000,
      },
    ],
    rooms: [
      {
        id: 1,
        name: 'Mermaid Rooms',
        fullName: 'Mermaid Rooms Mega Resort Karimunjawa',
        subtitle: 'For the whole year 24/7/365 Room 1, August',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
        rating: 9.7,
        ratingScale: '/10',
        reviewCount: 1420,
        price: 2000000,
        priceUnit: 'night',
        originalPrice: 2500000,
        discountPercent: 5,
        discountText: 'Save 5%',
        taxInfo: 'Include All Taxed',
        badge: 'BEST OPTION TO STAY',
        category: 'BASIC BACK COTTAGE',
        isFeatured: true,
        tags: ['Price includes breakfast', 'Best Sunset'],
        specs: {
          totalRooms: '1 King + 2',
          bathroom: '3 Attached',
          internet: '100Mbps',
          coveredParking: 'Yes Two',
        },
        highlights: {
          cleanliness: 'A well-maintained cottage with high standards of cleanliness,',
          amenities: 'Equipped with essential amenities to provide convenience',
        },
      },
      {
        id: 2,
        name: 'Nemo Rooms',
        fullName: 'Nemo Rooms Mega Resort Karimunjawa',
        subtitle: 'For the whole year 24/7/365 Room 2, August',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
        rating: 9.9,
        ratingScale: '/10',
        reviewCount: 2190,
        price: 2000000,
        priceUnit: 'night',
        originalPrice: 2500000,
        discountPercent: 5,
        discountText: 'Save 5%',
        taxInfo: 'Include All Taxed',
        badge: 'BEST OPTION TO STAY',
        category: 'BASIC BACK COTTAGE',
        isFeatured: true,
        tags: ['Price includes breakfast', 'Best Sunset'],
        specs: {
          totalRooms: '1 King + 2',
          bathroom: '3 Attached',
          internet: '100Mbps',
          coveredParking: 'Yes Two',
        },
        highlights: {
          cleanliness: 'A well-maintained cottage with high standards of cleanliness,',
          amenities: 'Equipped with essential amenities to provide convenience',
        },
      },
      {
        id: 3,
        name: 'Cemara Rooms',
        fullName: 'Cemara Rooms Mega Resort Karimunjawa',
        subtitle: 'For the whole year 24/7/365 Room 3, August',
        image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
        rating: 9.8,
        ratingScale: '/10',
        reviewCount: 1850,
        price: 2000000,
        priceUnit: 'night',
        originalPrice: 2500000,
        discountPercent: 5,
        discountText: 'Save 5%',
        taxInfo: 'Include All Taxed',
        badge: 'BEST OPTION TO STAY',
        category: 'BASIC BACK COTTAGE',
        isFeatured: true,
        tags: ['Price includes breakfast', 'Best Sunset'],
        specs: {
          totalRooms: '1 King + 2',
          bathroom: '3 Attached',
          internet: '100Mbps',
          coveredParking: 'Yes Two',
        },
        highlights: {
          cleanliness: 'A well-maintained cottage with high standards of cleanliness,',
          amenities: 'Equipped with essential amenities to provide convenience',
        },
      },
      {
        id: 4,
        name: 'Mahi - Mahi Rooms',
        fullName: 'Mahi - Mahi Rooms Mega Resort Karimunjawa',
        subtitle: 'For the whole year 24/7/365 Room 4, August',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        rating: 9.8,
        ratingScale: '/10',
        reviewCount: 1640,
        price: 2000000,
        priceUnit: 'night',
        originalPrice: 2500000,
        discountPercent: 5,
        discountText: 'Save 5%',
        taxInfo: 'Include All Taxed',
        badge: 'BEST OPTION TO STAY',
        category: 'BASIC BACK COTTAGE',
        isFeatured: false,
        tags: ['Price includes breakfast', 'Best Sunset'],
        specs: {
          totalRooms: '1 King + 2',
          bathroom: '3 Attached',
          internet: '100Mbps',
          coveredParking: 'Yes Two',
        },
        highlights: {
          cleanliness: 'A well-maintained cottage with high standards of cleanliness,',
          amenities: 'Equipped with essential amenities to provide convenience',
        },
      },
    ],
    dining: {
      id: 1,
      title: 'A Taste of Coastal Elegance',
      subtitle: 'Romantic Dining',
      description: 'Experience extraordinary culinary craft where fresh seafood from local fishermen meets fine Indonesian herbs and tropical spices. Whether a relaxed champagne breakfast on your private veranda or an intimate candlelit dinner on the beach, every dish is prepared to perfection.',
      highlight: 'Fresh Seafood BBQ & Candlelit Beachfront Tables',
      imagePrimary: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      imageSecondary: 'https://images.unsplash.com/photo-1533777857889-4be7c70e33f7?auto=format&fit=crop&w=800&q=80',
    },
    packages: [
      {
        id: 1,
        title: 'Stay Package',
        category: 'Stay Package',
        duration: '3 Days',
        bestSeason: '10 - 13 Apr',
        price: 2000000,
        priceUnit: '2 Person',
        image: '/images/package-stay.jpg',
        badge: 'Best Value',
        rating: 9.7,
        ratingScale: '/10',
        reviewCount: 3213,
        description: 'Experience a refined beachfront stay with stunning ocean views, private spaces, and warm hospitality — perfect for those seeking tranquility and comfort in a tropical paradise.',
        tags: [
          'Beachfront Villa',
          'Ocean View',
          'Private Terrace',
          'Infinity Pool',
          'Resort Facilities',
        ],
        includes: [
          'Roundtrip Fast Boat Ticket',
          '2 Nights Overwater Villa Stay',
          'Daily Breakfast & Seafood BBQ',
          'Snorkeling Gear & Underwater Photography',
          'Island Hopping Tour',
        ],
      },
      {
        id: 2,
        title: 'Island Explorer',
        category: 'Island Explorer',
        duration: '3 Days',
        bestSeason: '15 - 18 May',
        price: 3500000,
        priceUnit: '2 Person',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
        badge: 'Best Seller',
        rating: 9.8,
        ratingScale: '/10',
        reviewCount: 2450,
        description: 'Our signature island getaway package including express fast boat transfers, guided snorkeling across coral sanctuaries, and private island sunset barbecue.',
        tags: [
          'Snorkeling Gear',
          'Island Hopping',
          'Speedboat Transfer',
          'Sunset BBQ',
          'Tour Guide',
        ],
        includes: [
          'VIP Fast Boat Transfer',
          'Snorkeling Across 3 Spots',
          'Sunset Island BBQ Dinner',
          'Underwater Drone Video',
        ],
      },
      {
        id: 3,
        title: 'Honeymoon Escape',
        category: 'Honeymoon Escape',
        duration: '4 Days',
        bestSeason: '01 - 04 Jun',
        price: 6850000,
        priceUnit: '2 Person',
        image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=80',
        badge: 'Honeymoon Choice',
        rating: 9.9,
        ratingScale: '/10',
        reviewCount: 1890,
        description: 'A deeply romantic retreat with private sunset cruise, candlelit beachfront dinner, couple spa ritual, and luxury overwater suite with champagne welcome.',
        tags: [
          'Sunset Cruise',
          'Candlelight Dinner',
          'Couple Spa',
          'Floating Breakfast',
          'Overwater Suite',
        ],
        includes: [
          '3 Nights Luxury Water Villa',
          'Private Sunset Yacht Cruise',
          'Couples Aromatherapy Spa (90 min)',
          'Champagne & Floating Breakfast',
        ],
      },
      {
        id: 4,
        title: 'Diving Adventure',
        category: 'Diving Adventure',
        duration: '4 Days',
        bestSeason: '20 - 24 Jul',
        price: 4200000,
        priceUnit: '2 Person',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        badge: 'Adventure Choice',
        rating: 9.6,
        ratingScale: '/10',
        reviewCount: 1540,
        description: 'Immerse yourself into Karimunjawa vibrant underwater ecosystem with certified dive masters, wreck diving excursions, and coral garden explorations.',
        tags: [
          'PADI Dive Master',
          'Wreck Diving',
          'Underwater Photo',
          'All Meals Included',
          'Equipment',
        ],
        includes: [
          '4 Open Water Dive Sessions',
          'Full Scuba Equipment Rental',
          'Certified PADI Dive Master Guide',
          'Underwater 4K Video Documentation',
        ],
      },
    ],
    news: [
      {
        id: 1,
        title: 'The Easiest Way to Reach Mega Resort Karimunjawa',
        date: '27 September 2025',
        category: 'Travel Guide',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        excerpt: 'A welcoming and comfortable space designed to make your arrival smooth and relaxing, with warm hospitality a...',
        author: {
          name: 'Jenny Wilson',
          role: 'Web Designer',
          avatar: '',
          initials: 'PM',
        },
        readTime: '4 min read',
      },
      {
        id: 2,
        title: 'The Easiest Way to Reach Mega Resort Karimunjawa',
        date: '27 September 2025',
        category: 'Travel Guide',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        excerpt: 'A welcoming and comfortable space designed to make your arrival smooth and relaxing, with warm hospitality a...',
        author: {
          name: 'Jenny Wilson',
          role: 'Web Designer',
          avatar: '',
          initials: 'PM',
        },
        readTime: '5 min read',
      },
      {
        id: 3,
        title: 'The Easiest Way to Reach Mega Resort Karimunjawa',
        date: '27 September 2025',
        category: 'Travel Guide',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        excerpt: 'A welcoming and comfortable space designed to make your arrival smooth and relaxing, with warm hospitality a...',
        author: {
          name: 'Jenny Wilson',
          role: 'Web Designer',
          avatar: '',
          initials: 'PM',
        },
        readTime: '3 min read',
      },
    ],
    contact: {
      phone: '+62 812-3456-7890',
      whatsapp: '+62 812-3456-7890',
      email: 'reservations@megaresortkarimunjawa.com',
      address: 'Karimunjawa Islands, Jepara Regency, Central Java 59455, Indonesia',
      socials: {
        instagram: 'https://instagram.com/megaresort.karimunjawa',
        facebook: 'https://facebook.com/megaresortkarimunjawa',
        whatsapp: 'https://wa.me/6281234567890',
        youtube: 'https://youtube.com/@megaresortkarimunjawa',
      },
    },
  }
})
